-- ---------------------------------------------------------------------------
-- Where the archetypes went.
--
-- There was a table here — about sixty generic rows, "fried rice", "noodle
-- soup", a terminal "Mixed meal" at a hardcoded id — and a `seed_archetype_foods()`
-- that upserted them. They were tier 5 of the scan cascade: the floor a scan
-- landed on when the catalogue, the vision model or the network had failed it,
-- reached by classifying the plate over the fixed list and, failing even that,
-- by writing the terminal row with no model call and no query.
--
-- The argument for the floor was that a diary refusing a meal is worse than one
-- logging it roughly. It was wrong in the direction that matters. Nothing
-- downstream can tell a rough answer from a real one: the row sat on the day
-- with the user's own photograph on it, counted in the ring, the week, the
-- trends and the review, at 600 kcal nobody had eaten and nobody knew to check.
-- A scan that cannot say what the food is now says so, and the row on Today
-- offers another go.
--
-- The table went with the tier because nothing else read it. It was never
-- exposed to a client, no view joined it, and the pgTAP suite used it as a
-- convenient set of numbers rather than for anything it meant.
--
-- See the header of `functions/_shared/cascade.ts` for the cascade as it now
-- stands, and `31_daily_logs.sql` onwards for the tables that do carry a diary.
-- ---------------------------------------------------------------------------
