#!/usr/bin/env node
/**
 * Imports the design-system icon set into `assets/icons/` and regenerates the
 * static require map at `src/ui/icons.generated.ts`.
 *
 *   node scripts/sync-icons.mjs
 *
 * This is a developer tool, not a build step. The processed PNGs are committed,
 * so CI and EAS never run it — which is why it is allowed to depend on the
 * design system living at `.secrets/design-system` (gitignored) and on a
 * pngquant binary fetched through npx.
 *
 * Two transforms, both load-bearing:
 *
 * - Downscale 256 -> 192px. Nothing in the system renders an icon above 64pt,
 *   so 192px is @3x for the largest usage and @2x for the 96pt empty-state art.
 * - Quantise to a palette. These are flat illustrations with few colours;
 *   pngquant cuts them ~70% with no visible difference. Skipping it triples the
 *   bundle.
 *
 * Metro only bundles what the generated map requires, so an icon that is
 * deleted from `assets/` and from the map leaves the app entirely.
 */
import { execFileSync } from 'node:child_process'
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const APP = join(here, '..')
const SOURCE = join(APP, '..', '..', '.secrets', 'design-system', 'icons')
const DEST = join(APP, 'assets', 'icons')
const REGISTRY = join(APP, 'src', 'ui', 'icons.generated.ts')

const MAX_PX = 192
const QUALITY = '65-88'

if (!existsSync(SOURCE)) {
  console.error(`No design system at ${SOURCE}.`)
  console.error('Icons are committed under assets/icons, so this script is only')
  console.error('needed when the source set changes. Nothing to do.')
  process.exit(1)
}

const sets = readdirSync(SOURCE).filter((name) => statSync(join(SOURCE, name)).isDirectory())
if (!sets.length) {
  console.error(`No icon sets found under ${SOURCE}`)
  process.exit(1)
}

const run = (cmd, args) => execFileSync(cmd, args, { stdio: ['ignore', 'ignore', 'pipe'] })

/**
 * Resolve the pngquant binary once. Going through `npx` per file costs about a
 * second of module resolution each, which turns a 30-second job into 10 minutes.
 */
function pngquantBin() {
  run('npx', ['--yes', 'pngquant-bin@9', '--version'])
  const cache = join(process.env.HOME ?? '', '.npm', '_npx')
  const found = execFileSync('find', [cache, '-name', 'pngquant', '-type', 'f'], {
    encoding: 'utf8',
  })
    .split('\n')
    .filter(Boolean)
  if (!found.length)
    throw new Error('pngquant-bin installed but its binary was not found in the npx cache')
  return found[0]
}

const pngquant = pngquantBin()

rmSync(DEST, { recursive: true, force: true })

/** set -> sorted icon names, used for both the copy and the generated types. */
const manifest = {}
let bytes = 0

for (const set of sets.sort()) {
  mkdirSync(join(DEST, set), { recursive: true })
  const names = readdirSync(join(SOURCE, set))
    .filter((f) => f.endsWith('.png'))
    .map((f) => f.replace(/\.png$/, ''))
    .sort()

  for (const name of names) {
    const to = join(DEST, set, `${name}.png`)
    run('sips', ['-Z', String(MAX_PX), join(SOURCE, set, `${name}.png`), '--out', to])
    // pngquant refuses to overwrite in place without -f, and writes nothing at
    // all if it cannot hit the quality floor — hence --skip-if-larger off and a
    // post-check that the file still exists.
    run(pngquant, ['--quality', QUALITY, '--speed', '3', '-f', '-o', to, to])
    if (!existsSync(to)) throw new Error(`pngquant dropped ${set}/${name}`)
    bytes += statSync(to).size
  }

  manifest[set] = names
  console.log(`${set.padEnd(8)} ${String(names.length).padStart(3)} icons`)
}

const total = Object.values(manifest).reduce((n, names) => n + names.length, 0)

const entries = Object.entries(manifest)
  .map(([set, names]) => {
    const rows = names.map((n) => `    '${n}': require('../../assets/icons/${set}/${n}.png'),`)
    return `  ${set}: {\n${rows.join('\n')}\n  },`
  })
  .join('\n')

writeFileSync(
  REGISTRY,
  `// GENERATED by scripts/sync-icons.mjs — do not edit.
//
// React Native resolves \`require\` for assets at bundle time, so the paths have
// to be literal. That is the only reason this file exists: a runtime
// \`require(\\\`../../assets/icons/\${set}/\${name}.png\\\`)\` silently returns nothing.

export const icons = {
${entries}
} as const

export type IconSet = keyof typeof icons
export type IconName<S extends IconSet = IconSet> = keyof (typeof icons)[S]
`,
)

console.log(
  `\n${total} icons across ${sets.length} sets, ${(bytes / 1024 / 1024).toFixed(1)} MB` +
    `\nwrote ${REGISTRY.replace(APP, '.')}`,
)

// The design system ships a manifest of intended names. Anything listed there
// but missing on disk is a broken reference waiting to happen in a screen.
const manifestPath = join(SOURCE, 'manifest.json')
if (existsSync(manifestPath)) {
  const declared = JSON.parse(readFileSync(manifestPath, 'utf8'))
  for (const [set, names] of Object.entries(declared)) {
    const missing = names.filter((n) => !manifest[set]?.includes(n))
    if (missing.length)
      console.warn(`warn: ${set} declares but does not ship: ${missing.join(', ')}`)
  }
}
