/**
 * RiceCal design tokens — the single source of truth for colour.
 *
 * Two consumers, two shapes:
 *
 * 1. `ThemeProvider` publishes the active mode's `semantic` map as CSS custom
 *    properties, so Tailwind classes (`bg-surface`, `text-muted`) resolve to
 *    the right colour without a `dark:` prefix on every element in the app.
 *    `global.css` carries the light map as a static fallback, generated by
 *    `scripts/gen-theme-css.mjs` and guarded by `__tests__/tokens.test.ts`.
 * 2. Imperative code that cannot use a className — Skia canvases, victory
 *    charts, StatusBar, native header tints — reads `semantic` directly via
 *    `useThemeColors()`.
 *
 * Keep hex values UPPERCASE and six-digit: the drift test compares them
 * literally against the RGB triples in global.css.
 */

/** Brand ramps, independent of light/dark. Named after the food, not the role. */
export const palette = {
  /** Pandan — primary. Growth, "on track", the colour of a filled button. */
  pandan: '#2FBF71',
  pandanDeep: '#1B8A4E',
  /** Hibiscus — accent. Exercise, protein, destructive. Never used for alarm. */
  hibiscus: '#FF4D6D',
  hibiscusDeep: '#D62F4E',
  /** Kaya — carbs, rewards, "double check". */
  kaya: '#FFC145',
  kayaDeep: '#D99A1F',
  /** Water — hydration. */
  water: '#4CC9F0',
  waterDeep: '#1B87A8',
  /** Teh tarik — dietary fat. Warmth. */
  teh: '#C98B5E',
  tehDeep: '#A66C43',
} as const

/**
 * Role -> colour, per mode. Every key must exist in BOTH maps; a role defined
 * in only one resolves to nothing in the other, which renders as an invisible
 * element rather than an error. The test enforces it.
 */
const light = {
  // Surfaces. The system allows exactly two backgrounds plus one alt fill.
  canvas: '#F6F8F7',
  surface: '#FFFFFF',
  surfaceAlt: '#F0F4F1',
  /** The single inverted surface: snackbars, tooltips, fasting mode. */
  inverse: '#1C2321',
  onInverse: '#FFFFFF',
  inverseAccent: '#7BE3AC',

  // Lines and tracks.
  line: '#E4E8E5',
  track: '#EDF1EE',
  lineStrong: '#D6DCD8',

  // Text.
  ink: '#1C2321',
  heading: '#1B3A2B',
  body: '#495450',
  muted: '#6E7B74',
  faint: '#9AA5A0',

  // Disabled — a filled control that is off, not a surface.
  disabled: '#DFE4E1',
  disabledSlab: '#C9D1CC',
  onDisabled: '#9AA5A0',

  // Pandan.
  pandan: '#2FBF71',
  pandanSlab: '#1B8A4E',
  pandanSoft: '#EAF9F0',
  pandanSoftLine: '#CFEBDA',
  pandanInk: '#1B8A4E',
  onPandan: '#FFFFFF',

  // Hibiscus.
  hibiscus: '#FF4D6D',
  hibiscusSlab: '#D62F4E',
  hibiscusSoft: '#FFEEF1',
  hibiscusSoftLine: '#F7D2DA',
  hibiscusInk: '#D62F4E',
  onHibiscus: '#FFFFFF',

  // Kaya.
  kaya: '#FFC145',
  kayaSlab: '#D99A1F',
  kayaSoft: '#FFF3D6',
  kayaSoftLine: '#F0DDAE',
  kayaInk: '#3D2B14',
  onKaya: '#3D2B14',

  // Water.
  water: '#4CC9F0',
  waterSlab: '#1B87A8',
  waterSoft: '#EAF7FC',
  waterSoftLine: '#BEE6F5',
  waterInk: '#1B87A8',
  onWater: '#FFFFFF',

  // Teh tarik (fat).
  teh: '#C98B5E',
  tehSlab: '#A66C43',
} as const

/**
 * Dark twins, following the conversion table in the design system notes.
 *
 * Two rules that are easy to get wrong:
 * - Filled buttons flip their label to near-black (`onPandan`), because the
 *   accents get *brighter* in dark mode, not darker.
 * - `inverse` inverts too. A dark snackbar on a dark canvas would vanish, so
 *   the one inverted surface becomes light.
 */
const dark = {
  canvas: '#111716',
  surface: '#1A2220',
  surfaceAlt: '#202A27',
  inverse: '#F2F5F3',
  onInverse: '#0C1310',
  inverseAccent: '#1C6E44',

  line: '#2E3936',
  track: '#2E3936',
  lineStrong: '#3C4844',

  ink: '#F2F5F3',
  heading: '#F2F5F3',
  body: '#B9C4BF',
  muted: '#8B9A94',
  faint: '#6E7B74',

  disabled: '#3C4844',
  disabledSlab: '#2E3936',
  onDisabled: '#6E7B74',

  pandan: '#38D07E',
  pandanSlab: '#1C6E44',
  pandanSoft: '#14291F',
  pandanSoftLine: '#2E4A3C',
  pandanInk: '#38D07E',
  onPandan: '#0C1310',

  hibiscus: '#FF6B87',
  hibiscusSlab: '#B23A52',
  hibiscusSoft: '#33161C',
  hibiscusSoftLine: '#5E2A35',
  hibiscusInk: '#FF6B87',
  onHibiscus: '#0C1310',

  kaya: '#FFCE5E',
  kayaSlab: '#B27C1C',
  kayaSoft: '#3A3115',
  kayaSoftLine: '#6B5A2A',
  kayaInk: '#FFCE5E',
  onKaya: '#241C05',

  water: '#63D3F2',
  waterSlab: '#1E6E86',
  waterSoft: '#12262E',
  waterSoftLine: '#2E5A6B',
  waterInk: '#63D3F2',
  onWater: '#0C1310',

  teh: '#D6A277',
  tehSlab: '#8F6440',
} as const

export const semantic = { light, dark } as const

export type ColorRole = keyof typeof light
export type ThemeColors = Record<ColorRole, string>
export type ColorSchemeName = keyof typeof semantic

/** Spacing scale. 4 · 8 · 14 · 22 · 32, plus the three named layout values. */
export const spacing = {
  xs: 4,
  sm: 8,
  md: 14,
  lg: 22,
  xl: 32,
  /** Horizontal padding at the screen edge. */
  gutter: 20,
  /**
   * Interior padding of a card.
   *
   * The screen designs specify 18 on a 340pt frame; this is that, scaled to the
   * 393pt phones the app actually runs on. Set to 28 the cards read as roomy
   * panels rather than the compact tiles the designs draw.
   */
  card: 20,
  /** Vertical gap between stacked cards. */
  stack: 14,
} as const

/** Radius scale. Nothing in this app has a sharp corner. */
export const radius = {
  sm: 14,
  md: 20,
  tile: 22,
  sheet: 24,
  card: 28,
  full: 999,
} as const

/**
 * Slab depth — the solid drop under a squishy control. Not a blur: it is a
 * second rectangle, so it is rendered as a layer rather than a shadow.
 * See `Squish` for why.
 */
export const slab = {
  sm: 4,
  md: 5,
  lg: 6,
  hero: 7,
} as const

export const motion = {
  /** Press down. Fast enough to feel mechanical. */
  pressIn: 80,
  /** Release. Overshoots slightly via the easing curve. */
  pressOut: 320,
  /** Bars and rings fill once, on mount. */
  fill: 1200,
  /**
   * A panel arriving from an edge — the number pad.
   *
   * Close to what UIKit spends presenting a keyboard, because the pad stands in
   * for one: the footer riding up over a pad that moves at a different speed
   * from the keyboard it replaced reads as two separate events.
   */
  panel: 220,
} as const

/** Minimum touch targets, in points. */
export const hitSize = {
  /** Standard control height. */
  md: 56,
  /** Compact control height — the floor for anything tappable. */
  sm: 44,
  /** Hero / full-width CTA. */
  lg: 64,
} as const
