import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import tailwindConfig from '../../../tailwind.config.js'
import { hitSize, radius, semantic, spacing } from '../tokens'

const root = join(__dirname, '..', '..', '..')
const css = readFileSync(join(root, 'global.css'), 'utf8')

const hexToChannels = (hex: string) => {
  const n = Number.parseInt(hex.slice(1), 16)
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`
}

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)

const rootBlock = () => {
  const at = css.indexOf(':root {')
  expect(at).toBeGreaterThan(-1)
  return css.slice(at, css.indexOf('}', at))
}

describe('design tokens', () => {
  // ThemeProvider maps every role through `vars()` at runtime, so a role
  // present in one mode and missing in the other resolves to nothing at all —
  // an invisible element rather than a build error.
  it('defines every role in both modes', () => {
    expect(Object.keys(semantic.dark).sort()).toEqual(Object.keys(semantic.light).sort())
  })

  // global.css is generated by scripts/gen-theme-css.mjs, but nothing stops
  // someone hand-editing it. If that happens the app and the tokens module
  // disagree about what `bg-surface` means, and only one of them is visible.
  //
  // Light only: NativeWind has no dark-scoped stylesheet root, so the dark
  // palette lives entirely in ThemeProvider. See gen-theme-css.mjs.
  describe('global.css :root fallback', () => {
    const block = rootBlock()

    it.each(Object.entries(semantic.light))('--color-%s matches tokens.ts', (roleName, hex) => {
      expect(block).toContain(`--color-${kebab(roleName)}: ${hexToChannels(hex)};`)
    })
  })

  // The Tailwind config is CommonJS and cannot import tokens.ts, so the numeric
  // scales are transcribed there by hand. Catch the transcription going stale.
  describe('tailwind.config.js numeric scales', () => {
    const extend = tailwindConfig.theme?.extend as Record<string, Record<string, string>>

    it.each(Object.entries(spacing))('spacing.%s is %ipx', (key, value) => {
      expect(extend.spacing[key]).toBe(`${value}px`)
    })

    it.each(Object.entries(radius))('borderRadius.%s is %ipx', (key, value) => {
      expect(extend.borderRadius[key]).toBe(`${value}px`)
    })

    it.each(Object.entries(hitSize))('minHeight.%s is %ipx', (key, value) => {
      expect(extend.minHeight[key]).toBe(`${value}px`)
    })
  })
})
