-- ---------------------------------------------------------------------------
-- The shared food catalogue and the badge definitions.
--
-- GENERATED by supabase/scripts/gen-catalogue-sql.mjs from
-- apps/mobile/src/mock/{foods,fixtures}.ts. Do not edit by hand: regenerate,
-- or write a follow-up migration for a single correction.
--
-- Idempotent throughout. `on conflict do update` keyed on the slug means a
-- re-run repairs the catalogue instead of duplicating it, which matters
-- because this runs against production exactly like any other migration.
-- ---------------------------------------------------------------------------


-- 1. DISHES ------------------------------------------------------------------
--
-- `owner_id` stays null: these are catalogue rows, visible to every signed-in
-- user. `verified` stays false — the numbers are researched estimates for
-- Malaysian portions, not laboratory values, and the flag should say so.

insert into public.foods (slug, name, icon_set, icon_name, place, kcal, carbs_g, protein_g, fat_g)
values
  ('nasi-lemak-ayam', 'Nasi lemak ayam berempah', 'dishes', 'nasi-lemak', 'mamak', 640, 78, 27, 25),
  ('teh-tarik', 'Teh tarik kurang manis', 'dishes', 'teh-tarik', 'mamak', 135, 18, 3, 5),
  ('roti-canai', 'Roti canai', 'dishes', 'roti-canai', 'mamak', 301, 39, 6, 13),
  ('roti-telur', 'Roti telur', 'dishes', 'roti-telur', 'mamak', 398, 42, 12, 20),
  ('roti-canai-banjir', 'Roti canai banjir', 'dishes', 'roti-canai', 'mamak', 352, 46, 9, 14),
  ('roti-tisu', 'Roti tisu', 'dishes', 'murtabak', 'mamak', 410, 61, 7, 16),
  ('roti-planta', 'Roti planta', 'dishes', 'roti-telur', 'mamak', 330, 44, 6, 15),
  ('char-kuey-teow', 'Char kuey teow', 'dishes', 'char-kuey-teow', 'hawker', 742, 88, 24, 33),
  ('nasi-goreng-kampung', 'Nasi goreng kampung', 'dishes', 'nasi-goreng', 'hawker', 612, 82, 19, 22),
  ('chicken-rice', 'Nasi ayam', 'dishes', 'chicken-rice', 'kopitiam', 585, 72, 30, 18),
  ('laksa', 'Asam laksa', 'dishes', 'laksa', 'hawker', 432, 62, 18, 12),
  ('mee-goreng', 'Mee goreng mamak', 'dishes', 'mee-goreng', 'mamak', 660, 84, 20, 26),
  ('kaya-toast', 'Roti bakar kaya', 'dishes', 'kaya-toast', 'kopitiam', 285, 38, 6, 12),
  ('kopi-o', 'Kopi o kosong', 'dishes', 'kopi-o', 'kopitiam', 12, 2, 0, 0),
  ('half-boiled-eggs', 'Telur separuh masak', 'dishes', 'half-boiled-eggs', 'kopitiam', 155, 1, 13, 11),
  ('satay-ayam', 'Satay ayam', 'dishes', 'satay-celup', 'hawker', 290, 12, 28, 14),
  ('cendol', 'Cendol', 'dishes', 'cendol', 'hawker', 340, 56, 3, 12),
  ('milo-ais', 'Milo ais', 'dishes', 'milo-ais', 'mamak', 210, 34, 6, 6),
  ('nasi-campur', 'Nasi campur', 'dishes', 'nasi-campur', 'hawker', 690, 86, 28, 26),
  ('sup-kambing', 'Sup kambing', 'dishes', 'sup-kambing', 'mamak', 380, 12, 34, 22),
  ('yong-tau-foo', 'Yong tau foo', 'dishes', 'yong-tau-foo', 'hawker', 265, 22, 20, 11),
  ('popiah', 'Popiah basah', 'dishes', 'popiah', 'hawker', 185, 26, 6, 6),
  ('ayam-goreng', 'Ayam goreng berempah', 'dishes', 'ayam-goreng', 'mamak', 320, 8, 26, 21),
  ('water-plain', 'Air kosong', 'food', 'water-glass', 'home', 0, 0, 0, 0),
  ('protein-shake', 'Protein shake', 'food', 'protein-shaker', 'packaged', 128, 4, 24, 2),
  ('instant-noodles', 'Maggi goreng', 'food', 'instant-noodles', 'packaged', 430, 58, 9, 17),
  ('pisang-goreng', 'Pisang goreng', 'dishes', 'cucur-udang', 'hawker', 250, 38, 3, 10),
  ('apple', 'Epal', 'food', 'apple', 'home', 95, 25, 0, 0)
on conflict (slug) where owner_id is null do update
  set name      = excluded.name,
      icon_set  = excluded.icon_set,
      icon_name = excluded.icon_name,
      place     = excluded.place,
      kcal      = excluded.kcal,
      carbs_g   = excluded.carbs_g,
      protein_g = excluded.protein_g,
      fat_g     = excluded.fat_g;


-- 2. PORTIONS ----------------------------------------------------------------
--
-- Joined back to the dish by slug rather than by a uuid literal: the ids are
-- generated at insert time, and hardcoding them would make this migration
-- reproduce a specific run of itself rather than a state.

insert into public.food_servings (food_id, slug, label, factor, is_default, position)
select f.id, v.slug, v.label, v.factor, v.is_default, v.position
from (values
  ('nasi-lemak-ayam', 'plate', '1 plate', 1, true, 0),
  ('nasi-lemak-ayam', 'half', 'Half', 0.5, false, 1),
  ('nasi-lemak-ayam', 'g100', '100g', 0.4, false, 2),
  ('teh-tarik', 'cup', '1 cup', 1, true, 0),
  ('teh-tarik', 'small', 'Small', 0.7, false, 1),
  ('teh-tarik', 'large', 'Large', 1.4, false, 2),
  ('roti-canai', 'piece', '1 piece', 1, true, 0),
  ('roti-canai', 'half', 'Half', 0.5, false, 1),
  ('roti-canai', 'g100', '100g', 0.9, false, 2),
  ('roti-telur', 'piece', '1 piece', 1, true, 0),
  ('roti-telur', 'half', 'Half', 0.5, false, 1),
  ('roti-telur', 'g100', '100g', 0.9, false, 2),
  ('roti-canai-banjir', 'piece', '1 piece', 1, true, 0),
  ('roti-canai-banjir', 'half', 'Half', 0.5, false, 1),
  ('roti-canai-banjir', 'g100', '100g', 0.9, false, 2),
  ('roti-tisu', 'piece', '1 piece', 1, true, 0),
  ('roti-tisu', 'half', 'Half', 0.5, false, 1),
  ('roti-tisu', 'g100', '100g', 0.9, false, 2),
  ('roti-planta', 'piece', '1 piece', 1, true, 0),
  ('roti-planta', 'half', 'Half', 0.5, false, 1),
  ('roti-planta', 'g100', '100g', 0.9, false, 2),
  ('char-kuey-teow', 'plate', '1 plate', 1, true, 0),
  ('char-kuey-teow', 'half', 'Half', 0.5, false, 1),
  ('char-kuey-teow', 'g100', '100g', 0.4, false, 2),
  ('nasi-goreng-kampung', 'plate', '1 plate', 1, true, 0),
  ('nasi-goreng-kampung', 'half', 'Half', 0.5, false, 1),
  ('nasi-goreng-kampung', 'g100', '100g', 0.4, false, 2),
  ('chicken-rice', 'plate', '1 plate', 1, true, 0),
  ('chicken-rice', 'half', 'Half', 0.5, false, 1),
  ('chicken-rice', 'g100', '100g', 0.4, false, 2),
  ('laksa', 'bowl', '1 bowl', 1, true, 0),
  ('laksa', 'half', 'Half', 0.5, false, 1),
  ('laksa', 'large', 'Large', 1.5, false, 2),
  ('mee-goreng', 'plate', '1 plate', 1, true, 0),
  ('mee-goreng', 'half', 'Half', 0.5, false, 1),
  ('mee-goreng', 'g100', '100g', 0.4, false, 2),
  ('kaya-toast', 'piece', '1 piece', 1, true, 0),
  ('kaya-toast', 'half', 'Half', 0.5, false, 1),
  ('kaya-toast', 'g100', '100g', 0.9, false, 2),
  ('kopi-o', 'cup', '1 cup', 1, true, 0),
  ('kopi-o', 'small', 'Small', 0.7, false, 1),
  ('kopi-o', 'large', 'Large', 1.4, false, 2),
  ('half-boiled-eggs', 'piece', '1 piece', 1, true, 0),
  ('half-boiled-eggs', 'half', 'Half', 0.5, false, 1),
  ('half-boiled-eggs', 'g100', '100g', 0.9, false, 2),
  ('satay-ayam', 'five', '5 sticks', 1, true, 0),
  ('satay-ayam', 'ten', '10 sticks', 2, false, 1),
  ('satay-ayam', 'one', '1 stick', 0.2, false, 2),
  ('cendol', 'bowl', '1 bowl', 1, true, 0),
  ('cendol', 'half', 'Half', 0.5, false, 1),
  ('cendol', 'large', 'Large', 1.5, false, 2),
  ('milo-ais', 'cup', '1 cup', 1, true, 0),
  ('milo-ais', 'small', 'Small', 0.7, false, 1),
  ('milo-ais', 'large', 'Large', 1.4, false, 2),
  ('nasi-campur', 'plate', '1 plate', 1, true, 0),
  ('nasi-campur', 'half', 'Half', 0.5, false, 1),
  ('nasi-campur', 'g100', '100g', 0.4, false, 2),
  ('sup-kambing', 'bowl', '1 bowl', 1, true, 0),
  ('sup-kambing', 'half', 'Half', 0.5, false, 1),
  ('sup-kambing', 'large', 'Large', 1.5, false, 2),
  ('yong-tau-foo', 'piece', '1 piece', 1, true, 0),
  ('yong-tau-foo', 'half', 'Half', 0.5, false, 1),
  ('yong-tau-foo', 'g100', '100g', 0.9, false, 2),
  ('popiah', 'piece', '1 piece', 1, true, 0),
  ('popiah', 'half', 'Half', 0.5, false, 1),
  ('popiah', 'g100', '100g', 0.9, false, 2),
  ('ayam-goreng', 'piece', '1 piece', 1, true, 0),
  ('ayam-goreng', 'half', 'Half', 0.5, false, 1),
  ('ayam-goreng', 'g100', '100g', 0.9, false, 2),
  ('water-plain', 'cup', '1 cup', 1, true, 0),
  ('water-plain', 'small', 'Small', 0.7, false, 1),
  ('water-plain', 'large', 'Large', 1.4, false, 2),
  ('protein-shake', 'cup', '1 cup', 1, true, 0),
  ('protein-shake', 'small', 'Small', 0.7, false, 1),
  ('protein-shake', 'large', 'Large', 1.4, false, 2),
  ('instant-noodles', 'piece', '1 piece', 1, true, 0),
  ('instant-noodles', 'half', 'Half', 0.5, false, 1),
  ('instant-noodles', 'g100', '100g', 0.9, false, 2),
  ('pisang-goreng', 'piece', '1 piece', 1, true, 0),
  ('pisang-goreng', 'half', 'Half', 0.5, false, 1),
  ('pisang-goreng', 'g100', '100g', 0.9, false, 2),
  ('apple', 'piece', '1 piece', 1, true, 0),
  ('apple', 'half', 'Half', 0.5, false, 1),
  ('apple', 'g100', '100g', 0.9, false, 2)
) as v (food_slug, slug, label, factor, is_default, position)
join public.foods f on f.slug = v.food_slug and f.owner_id is null
on conflict (food_id, slug) do update
  set label      = excluded.label,
      factor     = excluded.factor,
      is_default = excluded.is_default,
      position   = excluded.position;


-- 3. BADGES ------------------------------------------------------------------
--
-- `key` is the i18n key the client already renders, so a badge and its label
-- are named the same thing in both places.

insert into public.achievements (key, icon_set, icon_name, tone, position)
values
  ('sevenDays', 'body', 'streak-chain', 'pandan', 0),
  ('protein', 'food', 'protein-block', 'hibiscus', 1),
  ('eightGlasses', 'food', 'water-glass', 'water', 2),
  ('photoPro', 'system', 'camera', 'kaya', 3),
  ('earlyBird', 'system', 'sunrise', 'pandan', 4),
  ('weekend', 'system', 'calendar', 'water', 5),
  ('thirtyDays', 'system', 'streak-calendar', 'pandan', 6),
  ('marathon', 'body', 'running-shoe', 'hibiscus', 7),
  ('perfectWeek', 'system', 'trophy', 'kaya', 8)
on conflict (key) do update
  set icon_set  = excluded.icon_set,
      icon_name = excluded.icon_name,
      tone      = excluded.tone,
      position  = excluded.position;

